- name: nexus namespace
  kubectl:
    file: templates/ns.yml

- name: nexus data volume
  delegate_to: "{{ cluster_delegate }}"
  kubectl:
    namespace: nexus
    content: "{{ lookup('template', 'volume-data.yml') }}"

- name: nexus deploy
  kubectl:
    namespace: nexus
    content: "{{ lookup('template', 'deploy.yml') }}"

- name: nexus service
  kubectl:
    namespace: nexus
    content: "{{ lookup('template', 'service.yml') }}"

- name: nexus ingress
  kubectl:
    namespace: nexus
    content: "{{ lookup('template', 'ingress.yml') }}"
