#jinja2: trim_blocks:False
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emby
  labels:
    k8s-app: emby
spec:
  replicas: 1
  serviceName: emby
  selector:
    matchLabels:
      k8s-app: emby
  template:
    metadata:
      labels:
        k8s-app: emby
    spec:
      nodeSelector:
        kubernetes.io/hostname: scylla

      containers:
        - name: emby-server
          image: "emby/embyserver:4.0.2.0"
          env:
            - name: UID
              value: "1000"
            - name: GID
              value: "100"

          ports:
            - containerPort: 8096
              name: http
            - containerPort: 8920
              name: https

          volumeMounts:
            - name: emby-config
              mountPath: /config
              readOnly: false
            - name: emby-movie
              mountPath: /emby-movie
              readOnly: false
            - name: emby-music
              mountPath: /emby-music
              readOnly: false
            - name: emby-tv
              mountPath: /emby-tv
              readOnly: false

      volumes:
        - name: emby-config
# {% if secrets.emby.volume.type == 'rbd' %}
          rbd: &rbd-volume
            <<: {{ secrets.ceph.volume | to_json }}
            monitors: {{ secrets.ceph.mons | map(attribute='hostname') | list | to_json }}
            readOnly: false
            pool: home-flash
            image: emby-config
# {% endif %}

        - name: emby-movie
# {% if secrets.emby.volume.type == 'rbd' %}
          rbd:
            <<: *rbd-volume
            pool: home-rust
            image: emby-movie
# {% endif %}

        - name: emby-music
# {% if secrets.emby.volume.type == 'rbd' %}
          rbd:
            <<: *rbd-volume
            pool: home-rust
            image: emby-music
# {% endif %}

        - name: emby-tv
# {% if secrets.emby.volume.type == 'rbd' %}
          rbd:
            <<: *rbd-volume
            pool: home-rust
            image: emby-tv
# {% endif %}
