apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: emby
  labels:
    k8s-app: emby
  annotations:
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
    certmanager.k8s.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - media.{{ secrets.domain }}
      secretName: media-{{ secrets.domain | replace(".", "-") }}-tls
  rules:
    - host: media.{{ secrets.domain }}
      http: &emby-http
        paths:
          - path: /
            backend:
              serviceName: emby
              servicePort: http