apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config
  labels:
    k8s-app: emby
spec:
  storageClassName: "{{ item.storage.class }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ item.storage.size }}"
  volumeMode: Filesystem
  volumeName: "{{ item.storage.name }}"