{
 "title": "Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cores",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_allocatable_cpu_cores / kube_node_status_capacity_cpu_cores",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_allocatable_memory_bytes / kube_node_status_capacity_memory_bytes",
     "legendFormat": "{{ node }} free"
    }
   ]
  },
  {
   "title": "Schedulable",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - kube_node_spec_unschedulable",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_node_status_condition{condition!='Ready',status='true'}",
     "legendFormat": "{{ node }} failing ({{ condition }})"
    },
    {
     "expr": "kube_node_status_condition{condition='Ready',status='true'}",
     "legendFormat": "{{ node }} ready"
    },
    {
     "expr": "kube_node_status_condition{condition!='Ready',status='unknown'}",
     "legendFormat": "{{ node }} unknown ({{ condition }})"
    },
    {
     "expr": "kube_node_status_condition{condition!='Ready',status='false'}",
     "legendFormat": "{{ node }} passing ({{ condition }})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Daemon Pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kube_daemonset_status_current_number_scheduled / kube_daemonset_status_desired_number_scheduled",
     "legendFormat": "{{namespace}}/{{daemonset}} ready"
    }
   ]
  },
  {
   "title": "Stateful Pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready / kube_statefulset_status_replicas",
     "legendFormat": "{{exported_namespace}}/{{statefulset}} ready"
    }
   ]
  },
  {
   "title": "Deployment Pods",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available / kube_deployment_status_replicas",
     "legendFormat": "{{exported_namespace}}/{{deployment}} ready"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count by (exported_pod) (kube_pod_status_phase{phase='Failed'}))",
     "legendFormat": "{{exported_namespace}}/{{exported_pod}} failed"
    }
   ]
  },
  {
   "title": "Running",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase='Running'}",
     "legendFormat": "{{exported_namespace}}/{{exported_pod}} running"
    }
   ]
  }
 ]
}