{
 "title": "Hypertables",
 "description": "Overview over TimescaleDB Hypertables and their space usage",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "database", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Hypertables",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(1) FROM _timescaledb_catalog.hypertable"
    }
   ]
  },
  {
   "title": "TimescaleDB",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "last_time",
   "targets": [
    {
     "rawSql": "SELECT extversion FROM pg_extension WHERE extname='timescaledb'"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT current_setting('server_version');"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(total_bytes) FROM _timescaledb_catalog.hypertable, hypertable_relation_size(table_name::text);"
    }
   ]
  },
  {
   "title": "Table Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(table_bytes) FROM _timescaledb_catalog.hypertable, hypertable_relation_size('prometheus.' || table_name::text);"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT sum(index_bytes) FROM _timescaledb_catalog.hypertable, hypertable_relation_size(table_name::text);"
    }
   ]
  },
  {
   "title": "Space Usage Hypertables",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \n  hypertable.table_name AS \"table_name\",\n  counts.schema_name as \"schema_name\",\n  counts.row_estimate AS \"row_count\",\n  sizes.table_bytes AS \"table_size\",\n  sizes.index_bytes AS \"index_size\",\n  sizes.total_bytes AS \"total_size\"\nFROM \n  _timescaledb_catalog.hypertable AS hypertable,\n  hypertable_relation_size(hypertable.table_name::text) AS sizes,\n  hypertable_approximate_row_count(hypertable.table_name::text) AS counts\nORDER BY total_bytes DESC;"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select table_name AS metric,to_timestamp(lower(ranges[1])/10^6) AS time ,total_bytes FROM _timescaledb_catalog.hypertable,chunk_relation_size(table_name::text) ORDER BY 1,2;\r\n"
    }
   ]
  }
 ]
}