{
 "title": "Network",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Interface Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInOctets[2m])",
     "legendFormat": "{{snmp_target}} {{ifIndex}} rx",
     "rawSql": "SELECT\n  time,\n  metric,\n  ((\n    CASE\n      WHEN value >= lag(value) OVER w\n        THEN value - lag(value) OVER w\n      WHEN lag(value) OVER w IS NULL THEN NULL\n      ELSE value\n    END\n  ) * 8) / EXTRACT(EPOCH FROM time - lag(time) OVER w) AS \"value\"\nFROM (\n  SELECT\n    CONCAT(labels->>'snmp_target', ' - ', labels->>'ifIndex') AS \"metric\",\n    $__timeGroupAlias(\"time\", $__interval, previous),\n    SUM(value) AS \"value\"\n  FROM prometheus.metrics\n  WHERE\n    $__timeFilter(\"time\")\n    AND name='ifInOctets'\n    AND value!='NaN'\n  GROUP BY metric, time\n  ORDER BY metric, time\n) AS samples\nWINDOW w AS (PARTITION BY metric ORDER BY time)\nORDER BY metric, time;"
    }
   ]
  },
  {
   "title": "Frames",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(dot1dTpPortOutFrames[2m])",
     "legendFormat": "{{ snmp_target }} {{dot1dTpPort}}"
    }
   ]
  },
  {
   "title": "Interface Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "ifSpeed",
     "legendFormat": "{{ snmp_target }} {{ ifIndex }}",
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  CONCAT(labels->'snmp_target', ' - ', labels->>'ifIndex') AS metric,\n  value\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") AND\n  name = 'ifHighSpeed' AND\n  value != 'NaN'\nORDER BY 2, 1"
    }
   ]
  }
 ]
}