{
 "title": "Nodes",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1",
     "legendFormat": "{{instance}}",
     "rawSql": "SELECT\n  uname.labels->>'nodename' AS \"metric\",\n  $__time(\"time\"),\n  metrics.value\nFROM metrics\nJOIN (\n  SELECT DISTINCT ON (\n    labels->>'instance'\n  )\n    labels\n  FROM metrics\n  WHERE name = 'node_uname_info'\n  ORDER BY labels->>'instance'\n) AS uname\nON uname.labels->>'instance' = metrics.labels->>'instance'\nWHERE\n  name = 'node_load1'\n  AND $__timeFilter(\"time\")\n  AND value != 'NaN'\nORDER BY metric, time;"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(uname.labels->>'nodename', ' - ', REGEXP_REPLACE(name, '.*_Mem(.*)_bytes', '\\1')) AS \"metric\",\n  $__time(\"time\"),\n  metrics.value\nFROM metrics\nJOIN (\n  SELECT DISTINCT ON (\n    labels->>'instance'\n  )\n    labels\n  FROM metrics\n  WHERE name = 'node_uname_info'\n  ORDER BY labels->>'instance'\n) AS uname\nON uname.labels->>'instance' = metrics.labels->>'instance'\nWHERE\n  name IN (\n    'node_memory_MemTotal_bytes',\n    'node_memory_MemFree_bytes',\n    'node_memory_MemAvailable_bytes'\n  ) AND\n  $__timeFilter(\"time\") AND\n  value != 'NaN'\nORDER BY metric, time;"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  metric,\n  (\n    CASE\n      WHEN value >= lag(value) OVER w\n        THEN value - lag(value) OVER w\n      WHEN lag(value) OVER w IS NULL THEN 0\n      ELSE value\n    END\n  ) / (\n    CASE\n      WHEN EXTRACT(epoch FROM INTERVAL '$__interval') > 30\n        THEN EXTRACT(epoch FROM INTERVAL '$__interval')\n      ELSE 30\n    END\n  ) AS \"value\"\nFROM (\n  SELECT\n    CONCAT(uname.labels->>'nodename', ' ', metrics.labels->>'device') AS \"metric\",\n    $__timeGroupAlias(\"time\", $__interval, previous),\n    MAX(metrics.value) AS \"value\"\n  FROM prometheus.metrics\n  \nJOIN (\n  SELECT DISTINCT ON (\n    labels->>'instance'\n  )\n    labels\n  FROM metrics\n  WHERE name = 'node_uname_info'\n  ORDER BY labels->>'instance'\n) AS uname\nON uname.labels->>'instance' = metrics.labels->>'instance'\n  WHERE\n    $__timeFilter(\"time\")\n    AND name='node_network_receive_bytes'\n    AND metrics.labels->>'device' NOT LIKE 'cali%'\n    AND value != 'NaN'\n  GROUP BY time, metric\n  ORDER BY time, metric\n) AS samples\nWINDOW w AS (PARTITION BY metric ORDER BY time)\nORDER BY metric, time;"
    },
    {
     "rawSql": "SELECT\n  time,\n  metric,\n  (\n    CASE\n      WHEN value >= lag(value) OVER w\n        THEN value - lag(value) OVER w\n      WHEN lag(value) OVER w IS NULL THEN 0\n      ELSE value\n    END\n  ) / 30 AS \"value\"\nFROM (\n  SELECT\n    CONCAT(labels->>'snmp_target', ' ', labels->>'ifIndex') AS \"metric\",\n    $__timeGroupAlias(\"time\", $__interval, previous),\n    MAX(value) AS \"value\"\n  FROM prometheus.metrics\n  WHERE\n    $__timeFilter(\"time\")\n    AND name = 'ifInOctets'\n    AND value != 'NaN'\n  GROUP BY metric, time\n  ORDER BY metric, time\n) AS samples\nWINDOW w AS (PARTITION BY metric ORDER BY time)\nORDER BY metric, time;"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(uname.labels->>'nodename', ' - ', metrics.labels->>'device', ' ', REGEXP_REPLACE(name, 'node_filesystem_(.*)_bytes', '\\1')) AS \"metric\",\n  $__time(\"time\"),\n  metrics.value\nFROM metrics\nJOIN (\n  SELECT DISTINCT ON (\n    labels->>'instance'\n  )\n    labels\n  FROM metrics\n  WHERE name = 'node_uname_info'\n  ORDER BY labels->>'instance'\n) AS uname\nON uname.labels->>'instance' = metrics.labels->>'instance'\nWHERE\n  $__timeFilter(\"time\") AND\n  metrics.name IN (\n    'node_filesystem_free_bytes',\n    'node_filesystem_size_bytes'\n  ) AND\n  metrics.labels->>'fstype' IN ('ext4', 'xfs') AND\n  metrics.labels->>'mountpoint' != '/boot' AND\n  metrics.value != 'NaN'\nORDER BY metric, time;"
    }
   ]
  },
  {
   "title": "Thermal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(uname.labels->>'nodename', ' ', REGEXP_REPLACE(metrics.labels->>'chip', '.*([0-9_]+)$', '\\1'), ' ', metrics.labels->>'sensor', ' (', sensors.labels->>'label', ')') AS \"metric\",\n  $__time(\"time\"),\n  metrics.value\nFROM metrics\nJOIN (\n  SELECT DISTINCT ON (\n    labels->>'instance'\n  )\n    labels\n  FROM metrics\n  WHERE \n    $__timeFilter(\"time\") AND\n    name = 'node_uname_info'\n  ORDER BY labels->>'instance'\n) AS uname\nON uname.labels->>'instance' = metrics.labels->>'instance'\nJOIN (\n  SELECT DISTINCT ON (\n    labels->>'instance', labels->>'chip', labels->>'sensor', labels->>'label'\n  ) labels\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") AND\n    name = 'node_hwmon_sensor_label'\n) AS sensors\nON \n  sensors.labels->>'instance' = metrics.labels->>'instance' AND\n  sensors.labels->>'chip' = metrics.labels->>'chip' AND\n  sensors.labels->>'sensor' = metrics.labels->>'sensor'\nWHERE\n  $__timeFilter(\"time\") AND\n  name = 'node_hwmon_temp_celsius' AND\n  sensors.labels->>'label' NOT IN ('tctl', 'tdie', 'phy_temperature') AND\n  value != 'NaN'\nORDER BY metric, time;"
    },
    {
     "rawSql": "SELECT\n  CONCAT(uname.labels->>'nodename', ' ', sensors.labels->>'label', ' (', REGEXP_REPLACE(metrics.labels->>'chip', '.*:(.*)', '\\1'), ')') AS \"metric\",\n  $__time(\"time\"),\n  metrics.value\nFROM metrics\nJOIN (\n  SELECT DISTINCT ON (\n    labels->>'instance'\n  )\n    labels\n  FROM metrics\n  WHERE \n    $__timeFilter(\"time\") AND\n    name = 'node_uname_info'\n  ORDER BY labels->>'instance'\n) AS uname\nON uname.labels->>'instance' = metrics.labels->>'instance'\nJOIN (\n  SELECT DISTINCT ON (\n    labels->>'instance', labels->>'chip', labels->>'sensor', labels->>'label'\n  ) labels\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") AND\n    name = 'node_hwmon_sensor_label'\n) AS sensors\nON \n  sensors.labels->>'instance' = metrics.labels->>'instance' AND\n  sensors.labels->>'chip' = metrics.labels->>'chip' AND\n  sensors.labels->>'sensor' = metrics.labels->>'sensor' \nWHERE\n  $__timeFilter(\"time\") AND\n  name = 'node_hwmon_temp_celsius' AND\n  sensors.labels->>'label' IN ('tctl', 'tdie') AND\n  value != 'NaN'\nORDER BY metric, time;"
    },
    {
     "rawSql": "SELECT\n  CONCAT(uname.labels->>'nodename', ' ', sensors.labels->>'label', ' (', REGEXP_REPLACE(metrics.labels->>'chip', '.*:(.*)', '\\1'), ')') AS \"metric\",\n  $__time(\"time\"),\n  metrics.value / 100\nFROM metrics\nJOIN (\n  SELECT DISTINCT ON (\n    labels->>'instance'\n  )\n    labels\n  FROM metrics\n  WHERE \n    $__timeFilter(\"time\") AND\n    name = 'node_uname_info'\n  ORDER BY labels->>'instance'\n) AS uname\nON uname.labels->>'instance' = metrics.labels->>'instance'\nJOIN (\n  SELECT DISTINCT ON (\n    labels->>'instance', labels->>'chip', labels->>'sensor', labels->>'label'\n  ) labels\n  FROM metrics\n  WHERE\n    $__timeFilter(\"time\") AND\n    name = 'node_hwmon_sensor_label'\n) AS sensors\nON \n  sensors.labels->>'instance' = metrics.labels->>'instance' AND\n  sensors.labels->>'chip' = metrics.labels->>'chip' AND\n  sensors.labels->>'sensor' = metrics.labels->>'sensor'\nWHERE\n  $__timeFilter(\"time\") AND\n  name = 'node_hwmon_temp_celsius' AND\n  sensors.labels->>'label' = 'phy_temperature' AND\n  value != 'NaN'\nORDER BY metric, time;"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "upsInfoLoadValue", "legendFormat": "UPS" }
   ]
  },
  { "title": "Frequency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "AMD Cores",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "node_cpu_frequency_hertz{instance=\"10.2.1.192:9100\"}",
     "legendFormat": "{{instance}}/{{cpu}}"
    }
   ]
  },
  {
   "title": "Intel Cores",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "node_cpu_frequency_hertz{instance=~\"10\\\\.2\\\\.1\\\\.(193|200):9100\"}",
     "legendFormat": "{{instance}}/{{cpu}}"
    }
   ]
  }
 ]
}