{
 "title": "Power",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PSU Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  labels->>'snmp_target' AS \"metric\",\n  $__time(\"time\"),\n  COUNT(name) AS \"value\"\nFROM metrics\nWHERE\n  $__timeFilter(\"time\") AND\n  name IN ('mtxrHlPowerSupplyState', 'mtxrHlBackupPowerSupplyState')\nGROUP BY metric, time\nORDER BY metric, time;"
    }
   ]
  },
  {
   "title": "SFP+ Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "mvolt" }
   ],
   "targets": [
    { "expr": "mtxrOpticalSupplyVoltage", "legendFormat": "{{ mtxrOpticalIndex }}" }
   ]
  },
  { "title": "UPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "upsInfoLoadValue", "legendFormat": "Load" }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "0 - upsInputVoltageValue", "legendFormat": "Input" },
    { "expr": "upsOutputVoltageValue", "legendFormat": "Output" },
    { "expr": "upsBatteryVoltageValue", "legendFormat": "Battery (Actual)" },
    { "expr": "upsBatteryVoltageNominal", "legendFormat": "Battery (Nominal)" },
    { "expr": "0 - upsInputVoltageNominal", "legendFormat": "Input (Nominal)" }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "upsBatteryRuntimeValue", "legendFormat": "remaining" },
    { "expr": "upsBatteryRuntimeLow", "legendFormat": "low" }
   ]
  },
  {
   "title": "Battery Level",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "upsBatteryChargeValue", "legendFormat": "current charge" },
    { "expr": "upsBatteryChargeLow", "legendFormat": "low battery" },
    { "expr": "upsBatteryChargeWarning", "legendFormat": "warning" }
   ]
  }
 ]
}