{
 "title": "Printer",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "temperature_tool0_actual", "legendFormat": "hotend (actual)" },
    { "expr": "temperature_tool0_target", "legendFormat": "hotend (target)" },
    { "expr": "temperature_bed_actual", "legendFormat": "bed (actual)" },
    { "expr": "temperature_bed_target", "legendFormat": "bed (target)" }
   ]
  },
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "printing" }
   ]
  },
  {
   "title": "Print Progress",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "progress", "legendFormat": "progress" }
   ]
  },
  {
   "title": "Position",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "movement_x", "legendFormat": "X" },
    { "expr": "movement_y", "legendFormat": "Y" },
    { "expr": "movement_z", "legendFormat": "Z" }
   ]
  }
 ]
}