apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescale-{{ item.name }}-adapter
  labels: &labels
    k8s-app: timescale
    "{{ secrets.dns.base }}/timescale-name": "{{ item.name }}"
    "{{ secrets.dns.base }}/timescale-role": "adapter"
spec:
  serviceName: timescale-adapter
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      nodeSelector: {{ item.selector | to_json }}
      containers:
        - name: adapter
          image: "ssube/prometheus-sql-adapter:master"
          imagePullPolicy: Always
          args:
            - --log.level=info
            - --pg.conn-str=host=timescale-{{ item.name }}.{{ item.namespace }}.svc.{{ secrets.dns.cluster }}.{{ secrets.dns.base }}
              dbname={{ item.postgres.name }}
              user={{ item.postgres.name }}
              password={{ item.postgres.pass }}
              sslmode=disable
            - --pg.max-open=8
            - --pg.max-idle=4
            # allowed metrics
            - --allow=kubelet_
            - --allow=node_
          ports:
            - containerPort: 9201
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi