apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescale-{{ item.name }}-adapter
  labels: &labels
    k8s-app: timescale
    "{{ secrets.dns.base }}/timescale/name": "{{ item.name }}"
    "{{ secrets.dns.base }}/timescale/role": "adapter"
spec:
  serviceName: timescale-adapter
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      nodeSelector: {{ item.selector | to_json }}
      containers:
        - name: adapter
          image: "timescale/prometheus-postgresql-adapter:0.4.1"
          args:
            - -log.level=info
            - -pg.host=timescale-{{ item.name }}.monitor.svc.{{ secrets.dns.cluster }}.{{ secrets.dns.base }}
            - -pg.user={{ item.user }}
            - -pg.password={{ item.pass }}
            - -pg.database={{ item.name }}
            - -pg.schema=prometheus
            - -pg.use-timescaledb
            - -pg.db-connect-retries=3
            - -pg.max-open-conns=8
            - -pg.max-idle-conns=4
          ports:
            - containerPort: 9201
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi