apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    k8s-app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        k8s-app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:{{ postgres_instance.version }}
        env:
          - name: PGDATA
            value: /data/postgres/pgdata
          - name: POSTGRES_PASSWORD
            value: "{{ postgres_instance.root.pass }}"
        ports:
        - name: db
          containerPort: 5432
        volumeMounts:
          - name: postgres-data
            mountPath: /data/postgres
            readOnly: false

      nodeSelector: {{ postgres_instance.selector | to_json }}
      volumes:
        - name: postgres-config
          secret:
            secretName: postgres-config
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data