apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    k8s-app: postgres

spec:
  storageClassName: "{{ postgres_instance.storage.class }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ postgres_instance.storage.size }}"
  volumeName: "{{ postgres_instance.storage.name }}"