apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    k8s-app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: redis
  serviceName: redis
  template:
    metadata:
      labels:
        k8s-app: redis
    spec:
      containers:
        - name: redis
          image: redis:4-alpine
          ports:
            - name: db
              containerPort: 6379
      nodeSelector: {{ redis_instance.selector | to_json }}
