- name: admin group
  group:
    name: admin

- name: admin sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD:ALL'

- name: user
  user:
    name: "{{ item.name }}"
    create_home: True
    groups: "{{ item.groups }}"
  when: "'key' in item"
  loop: "{{ secrets.users }}"

- name: user keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  loop: "{{ secrets.users | subelements('keys') }}"