- name: monitor namespace
  delegate_to: "{{ cluster_delegate }}"
  k8s:
    kubeconfig: "{{ cluster_context }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitor