# monitoring datastore
- name: timescale data volume
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'volume-data.yml') }}"
  vars:
    item: "{{ secrets.timescale }}"

- name: timescale server deploy
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'deploy-server.yml') }}"
  vars:
    item: "{{ secrets.timescale }}"

- name: timescale service
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'service.yml') }}"
  vars:
    item: "{{ secrets.timescale }}"

- name: wait for timescale to be available
  check_mode: no
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    command:
      - get
      - pods
      - -l=k8s-app=timescale
      - --field-selector=status.phase=Running
  register: timescale_result
  until: timescale_result.stdout.find("Running") != -1
  retries: 6
  delay: 10

- name: timescale adapter deploy
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'deploy-adapter.yml') }}"
  vars:
    item: "{{ secrets.timescale }}"

- name: timescale prune account
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'account-prune.yml') }}"
  vars:
    item: "{{ secrets.timescale }}"

- name: timescale prune role
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'role-prune.yml') }}"
  vars:
    item: "{{ secrets.timescale }}"

- name: timescale prune bind
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'bind-prune.yml') }}"
  vars:
    item: "{{ secrets.timescale }}"

- name: timescale prune job
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'job-prune.yml') }}"
  vars:
    item: "{{ secrets.timescale }}"

- name: prometheus role
  postgresql_user:
    <<: &k8s-timescale
      login_host: "timescale.monitor.svc.cluster.{{ secrets.dns.base }}"
      login_password: "{{ secrets.timescale.root.pass }}"
      login_user: postgres

    name: "{{ secrets.timescale.prometheus.user }}"
    password: "{{ secrets.timescale.prometheus.pass }}"

- name: prometheus database
  postgresql_db:
    <<: *k8s-timescale
    name: prometheus
    owner: "{{ secrets.timescale.prometheus.user }}"
