apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptimerobot-exporter
  labels:
    k8s-app: uptimerobot-exporter
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - monitor
  selector:
    matchLabels:
      k8s-app: uptimerobot-exporter