- name: apply calico custom resources
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    content: "{{ lookup('template', 'crd.yml') }}"

- name: apply calico account
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    content: "{{ lookup('template', 'account.yml') }}"

- name: apply calico role
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    content: "{{ lookup('template', 'role.yml') }}"

- name: apply calico role binding
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    content: "{{ lookup('template', 'role-binding.yml') }}"

- name: apply calico config
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    content: "{{ lookup('template', 'config.yml') }}"

- name: apply calico daemon
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    content: "{{ lookup('template', 'daemon.yml') }}"