- name: allow service ports
  retries: 3
  delay: 1
  ufw:
    rule: allow
    proto: "{{ item.protocol }}"
    to_port: "{{ item.port }}"
  with_items:
    - port: "22"
      protocol: tcp
    - port: "80"
      protocol: tcp
    - port: "443"
      protocol: tcp
    - port: "2200:2201"
      protocol: tcp
    - port: "30000:32767"
      protocol: tcp
    - port: "30000:32767"
      protocol: udp