apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner
  labels:
    k8s-app: gitlab-runner

subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: gitlab

roleRef:
  kind: ClusterRole
  name: gitlab-runner
  apiGroup: rbac.authorization.k8s.io