apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner
  labels:
    k8s-app: gitlab-runner

aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.{{ secrets.dns.base }}/gitlab-runner-role: "true"
rules: []

