apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-config-{{ item.name }}
  labels:
    k8s-app: gitlab-runner

type: Opaque
data:
  script: {{ lookup('template', 'config/setup.sh') | b64encode }}
  template: {{ lookup('template', 'config/config.toml') | b64encode }}