apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secrets
  labels:
    k8s-app: gitlab-runner

type: Opaque
data:
# {% for name in secrets.runner.secrets.keys() | list %}
# {% set body = secrets.runner.secrets[name] %}
  "{{ name }}": "{{ body.value | b64encode }}"
# {% endfor %}