# cluster monitors
- name: cluster manager service
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'service-manager.yml') | from_yaml }}"

- name: cluster scheduler service
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'service-scheduler.yml') | from_yaml }}"

# service monitors
- name: cluster service monitors
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'monitor-' + item + '.yml') | from_yaml }}"
  with_items:
    - apiserver
    - kubelet
    - manager
    - metrics
    - scheduler