- name: apply emby server
  kubectl:
    content: "{{ lookup('template', 'deploy.yml') }}"

- name: apply emby service
  kubectl:
    content: "{{ lookup('template', 'service.yml') }}"

- name: apply emby ingress
  kubectl:
    content: "{{ lookup('template', 'ingress.yml') }}"