- name: apply nexus exporter deploy
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: "{{ secrets.monitor.namespace }}"
    content: "{{ lookup('template', 'deploy.yml') }}"

- name: apply nexus exporter service
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: "{{ secrets.monitor.namespace }}"
    content: "{{ lookup('template', 'service.yml') }}"
