# gitlab backup
- name: gitlab server backup account
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    namespace: gitlab
    content: "{{ lookup('template', 'account.yml') }}"

- name: gitlab server backup role
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    namespace: gitlab
    content: "{{ lookup('template', 'role.yml') }}"
 
- name: gitlab server backup role binding
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    namespace: gitlab
    content: "{{ lookup('template', 'role-binding.yml') }}"
  
- name: gitlab server backup job
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    namespace: gitlab
    content: "{{ lookup('template', 'job-backup.yml') }}"
