# gitlab backup
- name: gitlab server backup account
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab
    definition: "{{ lookup('template', 'server/backup-account.yml') | from_yaml }}"

- name: gitlab server backup role
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab
    definition: "{{ lookup('template', 'server/backup-role.yml') | from_yaml }}"
 
- name: gitlab server backup role binding
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab
    definition: "{{ lookup('template', 'server/backup-role-binding.yml') | from_yaml }}"
  
- name: gitlab server backup job
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab
    definition: "{{ lookup('template', 'server/backup.yml') | from_yaml }}"
 