- name: timescale prune account
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'account.yml') }}"
  loop: "{{ secrets.timescale_server }}"

- name: timescale prune role
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'role.yml') }}"
  loop: "{{ secrets.timescale_server }}"

- name: timescale prune bind
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'role-binding.yml') }}"
  loop: "{{ secrets.timescale_server }}"

- name: timescale prune job
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'job.yml') }}"
  loop: "{{ secrets.timescale_server }}"
