apiVersion: v1
kind: Service
metadata:
  name: timescale
spec:
  ports:
  - name: db
    port: 5432
    targetPort: db
  - name: http
    port: 80
    targetPort: http
  selector:
    k8s-app: timescale