# gitlab runners
- name: gitlab runner account
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab
    definition: "{{ lookup('template', 'runner/account.yml') | from_yaml }}"

- name: gitlab runner config
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab
    content: "{{ lookup('template', 'config.yml') | from_yaml }}"
  with_items: "{{ gitlab_runner.flavors }}"
 
- name: gitlab runner secrets
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab-jobs
    content: "{{ lookup('template', 'secrets.yml') | from_yaml }}"
 
- name: gitlab runner default role
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab
    content: "{{ lookup('template', 'role-default.yml') | from_yaml }}"
 
- name: gitlab runner job role
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab
    content: "{{ lookup('template', 'role-job.yml') | from_yaml }}"
 
- name: gitlab runner all roles
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab
    content: "{{ lookup('template', 'role-all.yml') | from_yaml }}"
 
- name: gitlab runner role binding
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab
    content: "{{ lookup('template', 'role-binding.yml') | from_yaml }}"

- name: gitlab runner deploy
  environment:
    KUBECONFIG: "{{ secrets.context }}"
  kubectl:
    namespace: gitlab
    content: "{{ lookup('template', 'deploy.yml') | from_yaml }}"
  with_items: "{{ gitlab_runner.flavors }}"
