apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  labels:
    k8s-app: gitlab
  annotations:
    nginx.ingress.kubernetes.io/enable-access-log: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m

spec:
  tls:
    - hosts:
        - git.{{ secrets.dns.base }}
      secretName: git-{{ secrets.dns.base | replace(".", "-") }}-tls
  rules:
    - host: git.{{ secrets.dns.base }}
      http:
        paths:
          - backend:
              serviceName: gitlab
              servicePort: 80