kind: Secret
apiVersion: v1
metadata:
  name: gitlab-config
type: Opaque
data:
  "gitlab.rb": "{{ lookup('template', 'config/config.rb') | b64encode }}"
  "gitlab-secrets.json": "{{ secrets.gitlab.secrets | to_nice_json(indent=2) | b64encode }}"
  "ssh_host_ecdsa_key": "{{ secrets.gitlab.ssh_keys.ecdsa.key | b64encode }}"
  "ssh_host_ecdsa_key.pub": "{{ secrets.gitlab.ssh_keys.ecdsa.pub | b64encode }}"
  "ssh_host_ed25519_key": "{{ secrets.gitlab.ssh_keys.ed25519.key | b64encode }}"
  "ssh_host_ed25519_key.pub": "{{ secrets.gitlab.ssh_keys.ed25519.pub | b64encode }}"
  "ssh_host_rsa_key": "{{ secrets.gitlab.ssh_keys.rsa.key | b64encode }}"
  "ssh_host_rsa_key.pub": "{{ secrets.gitlab.ssh_keys.rsa.pub | b64encode }}"