apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    k8s-app: gitlab
spec:
  type: ClusterIP
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: ssh
    - name: http
      protocol: TCP
      port: 80
      targetPort: workhorse
    - name: monitor
      protocol: TCP
      port: 9168
      targetPort: monitor
  selector:
    k8s-app: gitlab