apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-secrets
  labels:
    k8s-app: gitlab
spec:
  storageClassName: "{{ gitlab.storage.secrets.class }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ gitlab.storage.secrets.size }}"
  volumeMode: Filesystem
  volumeName: "{{ gitlab.storage.secrets.name }}"