apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    k8s-app: prometheus
    "{{ secrets.dns.base }}/prometheus": "{{ secrets.prometheus.name }}"
  name: "{{ secrets.prometheus.name }}"
  namespace: monitor
spec:
  additionalScrapeConfigs:
    name: prometheus-home-extra
    key: scrape.yml
  remoteWrite:
    - url: http://timescale.monitor.svc.{{ secrets.dns.cluster }}.{{ secrets.dns.base }}/write
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  retention: 2h
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  version: v2.8.1