apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels: &labels
    k8s-app: prometheus
    "{{ secrets.dns.base }}/prometheus": "{{ item.name }}"
  name: "{{ item.name }}"
  namespace: monitor
spec:
  additionalScrapeConfigs:
    name: prometheus-{{ item.name }}-scrape
    key: scrape.yml
  podMetadata:
    labels: *labels
  remoteWrite:
    - url: http://timescale-{{ item.postgres.name }}.{{ item.postgres.namespace }}.svc.{{ secrets.dns.cluster }}.{{ secrets.dns.base }}/write
      queueConfig:
        capacity: {{ item.queue.capacity }}
        minShards: {{ (item.queue.shards / 2) | round | int }}
        maxShards: {{ item.queue.shards }}
        maxSamplesPerSend: {{ item.queue.batch }}
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  retention: {{ item.retention }}
  scrapeInterval: {{ item.interval }}
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  version: v{{ item.version }}