apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    k8s-app: k8s
  name: k8s
spec:
  baseImage: quay.io/prometheus/prometheus
  remoteWrite:
    - url: http://timescale.monitor.svc.{{ secrets.dns.cluster }}.{{ secrets.dns.base }}/write
      queue_config:
        capacity: 50000
        max_shards: 10
        max_samples_per_send: 500
        batch_send_deadline: 10s
        max_retries: 3
        min_backoff: 100ms
        max_backoff: 1s

  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
  retention: 5m
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchExpressions:
    - key: k8s-app
      operator: Exists
  version: v2.4.2