apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus
    "{{ secrets.dns.base }}/prometheus": "{{ secrets.prometheus.name }}"
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    k8s-app: prometheus
    "{{ secrets.dns.base }}/prometheus": "{{ secrets.prometheus.name }}"