apiVersion: v1
kind: Service
metadata:
  name: kubewire-ui
  namespace: vpn
  labels:
    k8s-app: kubewire
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    k8s-app: kubewire