#jinja2: trim_blocks:False
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescale-server
  labels: &labels
    k8s-app: timescale
    "{{ secrets.dns.base }}/timescale": server
spec:
  serviceName: timescale-server
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      nodeSelector: {{ item.selector | to_json }}
      containers:
        - name: timescale
          image: "timescale/pg_prometheus:0.2.1"
          args:
            - -c
            - synchronous_commit=OFF
          env:
            - name: POSTGRES_PASSWORD
              value: "{{ item.root.pass }}"
            - name: PGDATA
              value: "/pg-data/{{ item.name }}"
          ports:
            - containerPort: 5432
              name: db
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 4Gi
          volumeMounts:
            - name: timescale-data
              mountPath: "/pg-data"
      volumes:
        - name: timescale-data
          rbd:
            <<: {{ secrets.ceph.volume | to_json }}
            monitors: {{ secrets.ceph.mons | map(attribute='hostname') | list | to_json }}
            readOnly: false
            pool: home-flash
            image: timescale-data