# prometheus instance
- name: prometheus service account
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'account.yml') | from_yaml }}"

- name: prometheus cluster role
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'role.yml') | from_yaml }}"

- name: prometheus role binding
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'role-binding.yml') | from_yaml }}"

- name: prometheus deploy
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'deploy.yml') | from_yaml }}"

- name: prometheus service
  kubectl:
    namespace: monitor
    file: "{{ role_path }}/templates/service.yml"
