# prometheus instance
- name: prometheus service account
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'account.yml') }}"
  loop: "{{ secrets.prometheus }}"

- name: prometheus cluster role
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'role.yml') }}"
  loop: "{{ secrets.prometheus }}"

- name: prometheus role binding
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'role-binding.yml') }}"
  loop: "{{ secrets.prometheus }}"

- name: prometheus scrape config
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'secret-scrape.yml') }}"
  loop: "{{ secrets.prometheus }}"

- name: prometheus deploy
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'deploy.yml') }}"
  loop: "{{ secrets.prometheus }}"

- name: prometheus service
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'service.yml') }}"
  loop: "{{ secrets.prometheus }}"

- name: prometheus monitor
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'monitor.yml') }}"
  loop: "{{ secrets.prometheus }}"