# prometheus instance
- name: prometheus service account
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'account.yml') }}"

- name: prometheus cluster role
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'role.yml') }}"

- name: prometheus role binding
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'role-binding.yml') }}"

- name: prometheus deploy
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'deploy.yml') }}"

- name: prometheus service
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'service.yml') }}"