apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescale-{{ item.name }}-adapter
  labels: &labels
    k8s-app: timescale
    "{{ secrets.dns.base }}/timescale-name": "{{ item.name }}"
    "{{ secrets.dns.base }}/timescale-role": "adapter"
spec:
  serviceName: timescale-adapter
  replicas: 2
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      nodeSelector: {{ item.selector | to_json }}
      containers:
        - name: adapter
          image: "ssube/prometheus-sql-adapter:master-postgres"
          imagePullPolicy: Always
          args:
            - --log.level=info
            - --pg.cache-size=160000
            - --pg.conn-str=host=timescale-{{ item.name }}.{{ item.namespace }}.svc.{{ secrets.dns.cluster }}.{{ secrets.dns.base }}
              dbname={{ secrets.dns.slug }}
              user={{ item.postgres.name }}
              password={{ item.postgres.pass }}
              sslmode=disable
            - --pg.max-open=8
            - --pg.max-idle=8
            # allowed metrics
            - --allow=adapter_
            - --allow=container_cpu_cfs_
            - --allow=container_cpu_delta
            - --allow=container_cpu_usage_seconds_total
            - --allow=container_memory_rss
            - --allow=container_spec_
            - --allow=grafana_
            - --allow=isolex_
            - --allow=kube_cronjob_status_
            - --allow=kube_daemonset_status_
            - --allow=kube_deployment_status_
            - --allow=kube_job_status_
            - --allow=kube_node_status_
            - --allow=kube_pod_container_status_
            - --allow=kube_pod_status_
            - --allow=kube_replicaset_status_
            - --allow=kube_statefulset_status_
            - --allow=kubelet_
            - --allow=nginx_
            - --allow=node_
            - --allow=nodejs_
            - --allow=process_
            - --allow=prometheus_
          ports:
            - containerPort: 9201
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 200Mi
