apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: timescale-adapter
  labels: &labels
    "{{ secrets.dns.base }}/timescale-name": "{{ item.name }}"
    "{{ secrets.dns.base }}/timescale-role": "adapter"
    k8s-app: timescale
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: http
      scheme: http
  jobLabel: "k8s-app"
  namespaceSelector:
    matchNames:
      - monitor
  selector:
    matchLabels: *labels
