apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  labels:
    k8s-app: snmp-exporter
spec:
  selector:
    k8s-app: snmp-exporter

  ports:
    - name: http
      port: 80
      targetPort: http