#jinja2: trim_blocks:False
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescale-{{ item.name }}-server
  labels: &labels
    k8s-app: timescale
    "{{ secrets.dns.base }}/timescale-name": "{{ item.name }}"
    "{{ secrets.dns.base }}/timescale-role": "server"
spec:
  serviceName: timescale-{{ item.name }}-server
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      nodeSelector: {{ item.selector | to_json }}
      containers:
        - name: server
          image: "timescale/timescaledb:{{ item.version }}"
          args:
            - -c
            - synchronous_commit=OFF
            - -c
            - shared_buffers=1GB
            - -c
            - effective_cache_size=3GB
            - -c
            - maintenance_work_mem=512MB
            - -c
            - work_mem=5242kB
            - -c
            - timescaledb.max_background_workers=8
            - -c
            - max_worker_processes=13
            - -c
            - max_parallel_workers_per_gather=1
            - -c
            - max_parallel_workers=2
            - -c
            - wal_buffers=16MB
            - -c
            - min_wal_size=4GB
            - -c
            - max_wal_size=8GB
            - -c
            - default_statistics_target=50
            - -c
            - random_page_cost=1.1
            - -c
            - checkpoint_completion_target=0.9
            - -c
            - max_connections=100
            - -c
            - max_locks_per_transaction=64
            - -c
            - autovacuum_max_workers=10
            - -c
            - autovacuum_naptime=10
            - -c
            - effective_io_concurrency=200
          env:
            - name: POSTGRES_PASSWORD
              value: "{{ item.root.pass }}"
            - name: PGDATA
              value: "/pg-data/{{ item.name }}"
          ports:
            - containerPort: 5432
              name: db
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 4Gi
          volumeMounts:
            - name: timescale-data
              mountPath: "/pg-data"
              readOnly: false

      volumes:
        - name: timescale-data
# {% if item.storage.type == 'pvc' %}
          persistentVolumeClaim:
            claimName: timescale-{{ item.name }}-data
# {% elif item.storage.type == 'rbd' %}
          rbd:
            <<: {{ secrets.ceph.volume | to_json }}
            monitors: {{ secrets.ceph.mons | map(attribute='hostname') | list | to_json }}
            readOnly: false
            pool: {{ item.storage.class }}
            image: {{ item.storage.name }}
# {% endif %}
