#jinja2: trim_blocks:False
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescale-{{ item.name }}-server
  labels: &labels
    k8s-app: timescale
    "{{ secrets.dns.base }}/timescale-name": "{{ item.name }}"
    "{{ secrets.dns.base }}/timescale-role": "server"
spec:
  serviceName: timescale-{{ item.name }}-server
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      nodeSelector: {{ item.selector | to_json }}
      containers:
        - name: server
          image: "timescale/timescaledb:{{ item.version }}"
          args:
            - -c
            - synchronous_commit=OFF
          env:
            - name: POSTGRES_PASSWORD
              value: "{{ item.root.pass }}"
            - name: PGDATA
              value: "/pg-data/{{ item.name }}"
          ports:
            - containerPort: 5432
              name: db
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 1000m
              memory: 4Gi
          volumeMounts:
            - name: timescale-data
              mountPath: "/pg-data"
              readOnly: false

      volumes:
        - name: timescale-data
# {% if item.storage.type == 'pvc' %}
          persistentVolumeClaim:
            claimName: timescale-{{ item.name }}-data
# {% elif item.storage.type == 'rbd' %}
          rbd:
            <<: {{ secrets.ceph.volume | to_json }}
            monitors: {{ secrets.ceph.mons | map(attribute='hostname') | list | to_json }}
            readOnly: false
            pool: {{ item.storage.class }}
            image: {{ item.storage.name }}
# {% endif %}