apiVersion: v1
kind: Service
metadata:
  name: timescale-{{ item.name }}
  labels: &labels
    k8s-app: timescale
    "{{ secrets.dns.base }}/timescale-name": "{{ item.name }}"
spec:
  ports:
  - name: db
    port: 5432
    targetPort: db
  - name: http
    port: 80
    targetPort: http
  selector: *labels