apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescale-{{ item.name }}-data
  labels:
    k8s-app: timescale
    "{{ secrets.dns.base }}/timescale-name": "{{ item.name }}"
spec:
  storageClassName: "{{ item.storage.class }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ item.storage.size }}"
  volumeMode: Filesystem
  volumeName: "{{ item.storage.name }}"