# grafana
- name: grafana config
  delegate_to: "{{ cluster_delegate }}"
  k8s:
    kubeconfig: "{{ cluster_context }}"
    namespace: monitor
    resource_definition: "{{ lookup('template', 'config.yml') | from_yaml }}"

- name: grafana data volume
  delegate_to: "{{ cluster_delegate }}"
  k8s:
    kubeconfig: "{{ cluster_context }}"
    namespace: monitor
    resource_definition: "{{ lookup('template', 'volume-data.yml') | from_yaml }}"
 
- name: grafana deploy
  delegate_to: "{{ cluster_delegate }}"
  k8s:
    kubeconfig: "{{ cluster_context }}"
    namespace: monitor
    resource_definition: "{{ lookup('template', 'deploy.yml') | from_yaml }}"
 
- name: grafana service
  delegate_to: "{{ cluster_delegate }}"
  k8s:
    kubeconfig: "{{ cluster_context }}"
    namespace: monitor
    resource_definition: "{{ lookup('template', 'service.yml') | from_yaml }}"
 
- name: grafana ingress
  delegate_to: "{{ cluster_delegate }}"
  shell: kubectl -n monitor apply -f "{{ role_path }}/templates/ingress.yml"
  environment:
    KUBECONFIG: "{{ cluster_context }}"
 
- name: grafana backup
  delegate_to: "{{ cluster_delegate }}"
  k8s:
    kubeconfig: "{{ cluster_context }}"
    namespace: monitor
    resource_definition: "{{ lookup('template', 'backup.yml') | from_yaml }}"