#jinja2: trim_blocks:False
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-{{ item.name }}
  labels: &labels
    k8s-app: postgres
    "{{ secrets.dns.base }}/postgres-name": "{{ item.name }}"
    "{{ secrets.dns.base }}/postgres-role": "server"
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  serviceName: postgres
  template:
    metadata:
      labels: *labels
    spec:
      nodeSelector: {{ item.selector | to_json }}
      containers:
      - name: server
        image: postgres:{{ item.version }}
        env:
          - name: PGDATA
            value: "/pg-data/{{ item.name }}"
          - name: POSTGRES_PASSWORD
            value: "{{ item.root.pass }}"
        ports:
        - name: db
          containerPort: 5432
        volumeMounts:
          - name: postgres-data
            mountPath: /pg-data
            readOnly: false

      volumes:
        - name: postgres-config
          secret:
            secretName: postgres-{{ item.name }}-config
        - name: postgres-data
# {% if item.storage.type == 'pvc' %}
          persistentVolumeClaim:
            claimName: postgres-{{ item.name }}-data
# {% elif item.storage.type == 'rbd' %}
          rbd:
            <<: {{ secrets.ceph.volume | to_json }}
            monitors: {{ secrets.ceph.mons | map(attribute='hostname') | list | to_json }}
            readOnly: false
            pool: {{ item.storage.class }}
            image: {{ item.storage.name }}
# {% endif %}