apiVersion: v1
kind: Service
metadata:
  name: uptimerobot-exporter
  labels:
    k8s-app: uptimerobot-exporter
spec:
  selector:
    k8s-app: uptimerobot-exporter

  ports:
    - name: metrics
      port: 9429
      targetPort: metrics