apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-backup
  labels:
    k8s-app: gitlab

subjects:
  - kind: ServiceAccount
    name: gitlab-backup
    namespace: gitlab

roleRef:
  kind: Role
  name: gitlab-backup
  apiGroup: rbac.authorization.k8s.io