- name: apply dns config
  kubectl:
    command: apply
    content: "{{ lookup('template', 'config.yml') }}"

- name: apply dns credentials secret
  kubectl:
    command: apply
    content: "{{ lookup('template', 'secret.yml') }}"

- name: apply dns deploy
  kubectl:
    command: apply
    file: templates/deploy.yml