- name: timescale adapter deploy
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'deploy.yml') }}"
  loop: "{{ secrets.timescale_adapter }}"