apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-express
  namespace: monitor
  labels:
    k8s-app: prometheus-express
subsets:
  - addresses:
    - ip: 10.2.1.220
    - ip: 10.2.1.221
    ports:
      - name: metrics
        port: 8080
        protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-express
  namespace: monitor
  labels:
    k8s-app: prometheus-express
spec:
  type: ExternalName
  externalName: 10.2.1.220
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    k8s-app: prometheus-express
