- name: apply coredns config
  environment:
    KUBECONFIG: "{{ secrets.cluster.context }}"
  kubectl:
    command: apply
    namespace: kube-system
    content: "{{ lookup('template', 'config.yml') }}"