# prometheus controller
- name: prometheus operator service account
  delegate_to: "{{ cluster_delegate }}"
  k8s:
    kubeconfig: "{{ cluster_context }}"
    namespace: monitor
    definition: "{{ lookup('template', 'account.yml') | from_yaml }}"

- name: prometheus operator cluster role
  delegate_to: "{{ cluster_delegate }}"
  k8s:
    kubeconfig: "{{ cluster_context }}"
    namespace: monitor
    definition: "{{ lookup('template', 'role.yml') | from_yaml }}"

- name: prometheus operator role binding
  delegate_to: "{{ cluster_delegate }}"
  k8s:
    kubeconfig: "{{ cluster_context }}"
    namespace: monitor
    definition: "{{ lookup('template', 'role-binding.yml') | from_yaml }}"

- name: prometheus operator deploy
  delegate_to: "{{ cluster_delegate }}"
  k8s:
    kubeconfig: "{{ cluster_context }}"
    namespace: monitor
    definition: "{{ lookup('template', 'deploy.yml') | from_yaml }}"

