# prometheus controller
- name: prometheus operator service account
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'account.yml') }}"

- name: prometheus operator cluster role
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'role.yml') }}"

- name: prometheus operator role binding
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'role-binding.yml') }}"

- name: prometheus operator deploy
  kubectl:
    namespace: monitor
    content: "{{ lookup('template', 'deploy.yml') }}"
