- name: disable wayland
  lineinfile:
    path: /etc/gdm3/custom.conf
    regexp: "^WaylandEnable="
    line: "WaylandEnable=false"

- name: install xfce
  apt:
    name:
      - xfce4
    state: latest

- name: install arc theme
  apt:
    name:
      - arc-theme
    state: latest
