apiVersion: v1
kind: Endpoints
metadata:
  name: ceph-metrics
  labels:
    k8s-app: ceph
subsets:
  - addresses: "{{ secrets.ceph.mons }}"
    ports:
      - name: metrics
        port: 9283
        protocol: TCP