#jinja2: trim_blocks:False
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  labels:
    k8s-app: grafana
spec:
  replicas: 1
  serviceName: grafana
  selector:
    matchLabels:
      k8s-app: grafana
  template:
    metadata:
      labels:
        k8s-app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:{{ secrets.grafana.version }}
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 3000

          readinessProbe:
            httpGet:
              path: /api/health
              port: http

          resources: {{ secrets.grafana.resources | to_json }}

          volumeMounts: &grafana-mounts
            - name: config
              mountPath: /etc/grafana
              readOnly: true
            - name: data
              mountPath: /data
              readOnly: false

      nodeSelector: {{ secrets.grafana.selector | to_json }}
      volumes:
        - name: config
          secret:
            secretName: grafana-config
        - name: data
# {% if secrets.grafana.volume.type == 'rbd' %}
          rbd:
            <<: {{ secrets.ceph.volume | to_json }}
            monitors: {{ secrets.ceph.mons | map(attribute='hostname') | list | to_json }}
            readOnly: false
            pool: home-flash
            image: grafana-data
# {% endif %}