apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  labels:
    k8s-app: grafana
spec:
  tls:
    - hosts:
        - metrics.{{ secrets.domain }}
      secretName: metrics-{{ secrets.domain | replace(".", "-") }}-tls
  rules:
    - host: metrics.{{ secrets.domain }}
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 80