apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  labels:
    k8s-app: grafana
spec:
  tls:
    - hosts:
        - metrics.{{ secrets.dns.base }}
      secretName: metrics-{{ secrets.dns.base | replace(".", "-") }}-tls
  rules:
    - host: metrics.{{ secrets.dns.base }}
      http:
        paths:
          - backend:
              serviceName: grafana
              servicePort: 80