apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: grafana-backup
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/exec
  verbs: ["create", "get", "list", "watch"]