apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nexus
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
  labels:
    k8s-app: nexus

spec:
  tls:
    - hosts:
        - artifacts.{{ secrets.dns.base }}
        - docker.artifacts.{{ secrets.dns.base }}
        - docker-push.artifacts.{{ secrets.dns.base }}
      secretName: artifacts-{{ secrets.dns.base | replace(".", "-") }}-tls
  rules:
    - host: artifacts.{{ secrets.dns.base }}
      http:
        paths:
          - backend:
              serviceName: nexus
              servicePort: 80
    - host: docker.artifacts.{{ secrets.dns.base }}
      http:
        paths:
          - backend:
              serviceName: nexus
              servicePort: 8011
    - host: docker-push.artifacts.{{ secrets.dns.base }}
      http:
        paths:
          - backend:
              serviceName: nexus
              servicePort: 8010
 