apiVersion: v1
kind: Service
metadata:
  name: nexus
  labels:
    k8s-app: nexus
spec:
  type: ClusterIP
  selector:
    k8s-app: nexus

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http

    - name: docker-in
      protocol: TCP
      port: 8010
      targetPort: docker-in

    - name: docker-out
      protocol: TCP
      port: 8011
      targetPort: docker-out